# Generated by Django 2.2.4 on 2019-08-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('createdByUser', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
                ('fullName', models.CharField(max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('createdByUser', models.EmailField(max_length=254)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalGov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDoc', models.CharField(max_length=15)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('dueDate', models.DateField()),
                ('active', models.BooleanField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company')),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.User')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company')),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.User')),
            ],
        ),
    ]
