# Generated by Django 2.2.4 on 2019-08-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rnc',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
