# Generated by Django 2.2.4 on 2019-09-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_fiscalgov_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='fiscalgov',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='companyId',
            new_name='company',
        ),
    ]
