# Generated by Django 2.2.4 on 2019-09-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20190904_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userHash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='userRole',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
