# Generated by Django 2.2.4 on 2019-09-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20190929_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='createdByUser',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='createdByUser',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalgov',
            name='createdByUser',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
