# Generated by Django 2.2.4 on 2019-09-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20190930_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='createdByUser',
            new_name='createdUser',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='createdByUser',
            new_name='createdUser',
        ),
        migrations.RenameField(
            model_name='fiscalgov',
            old_name='createdByUser',
            new_name='createdUser',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdByUser',
            new_name='createdUser',
        ),
    ]
