# Generated by Django 2.2.4 on 2019-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20190930_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
