# Generated by Django 2.2.4 on 2019-10-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20191002_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalgov',
            name='typeDoc',
            field=models.CharField(max_length=11),
        ),
    ]
