# Generated by Django 2.2.4 on 2019-10-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_fiscalgov_usedininvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalgov',
            name='usedInInvoice',
            field=models.IntegerField(default=0),
        ),
    ]
