# Generated by Django 2.2.4 on 2019-11-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='rnc',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
