# Generated by Django 2.2.4 on 2019-11-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_auto_20191120_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identification',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
