# Generated by Django 2.2.4 on 2019-12-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_customer_identificationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
