# Generated by Django 2.2.4 on 2019-08-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceId', models.IntegerField()),
                ('productId', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(max_length=20)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('ncf', models.CharField(max_length=13)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company')),
                ('createdByUsr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.User')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Customer')),
            ],
        ),
    ]
