# Generated by Django 2.2.4 on 2019-08-30 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesdetail',
            name='invoiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.InvoicesHeader'),
        ),
        migrations.AlterField(
            model_name='invoicesheader',
            name='ncf',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
