# Generated by Django 2.2.4 on 2019-08-30 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190830_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesdetail',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
