# Generated by Django 2.2.4 on 2019-08-31 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190830_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicesheader',
            old_name='createdByUsr',
            new_name='createdByUser',
        ),
    ]
