# Generated by Django 2.2.4 on 2019-09-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190831_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicesdetail',
            old_name='invoiceId',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoicesdetail',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='invoicesheader',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='invoicesheader',
            old_name='customerId',
            new_name='customer',
        ),
    ]
