# Generated by Django 2.2.4 on 2019-09-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190904_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesheader',
            name='sequence',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
