# Generated by Django 2.2.4 on 2019-09-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20190930_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicesheader',
            old_name='createdByUser',
            new_name='createdUser',
        ),
    ]
