# Generated by Django 2.2.4 on 2019-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20190930_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesheader',
            name='detail',
            field=models.ManyToManyField(to='sales.InvoicesDetail'),
        ),
    ]
