# Generated by Django 2.2.4 on 2019-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_invoicesheader_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesheader',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
