# Generated by Django 2.2.4 on 2019-10-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_invoicesheader_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesdetail',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesdetail',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
