# Generated by Django 2.2.4 on 2019-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20191006_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
