# Generated by Django 2.2.4 on 2019-11-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_invoicessequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesheader',
            name='serverDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
