# Generated by Django 2.2.4 on 2019-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_invoicesheader_serverdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesheader',
            name='creationDate',
            field=models.DateTimeField(),
        ),
    ]
