# Generated by Django 2.2.4 on 2019-11-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20191118_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesheader',
            name='sequence',
            field=models.IntegerField(),
        ),
    ]
