# Generated by Django 2.2.4 on 2019-12-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20191118_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesdetail',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicesdetail',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicesdetail',
            name='itbis',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicesdetail',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicesdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicesheader',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicesheader',
            name='itbis',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicesheader',
            name='subtotal',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
