# Generated by Django 2.2.4 on 2020-03-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20191219_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesheader',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
