# Generated by Django 2.2.4 on 2021-02-16 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210130_1223'),
        ('administration', '0022_auto_20191219_1738'),
        ('sales', '0022_invoicesleaddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationsHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('paymentMethod', models.CharField(max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('itbis', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('creationDate', models.DateTimeField()),
                ('createdUser', models.EmailField(blank=True, max_length=254, null=True)),
                ('serverDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('printed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('itbis', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.QuotationsHeader')),
            ],
        ),
    ]
