# Generated by Django 2.2.4 on 2021-02-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_quotationsdetail_quotationsheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesleaddetail',
            name='invoice',
        ),
        migrations.CreateModel(
            name='InvoicesLeadHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.InvoicesHeader')),
            ],
        ),
        migrations.AddField(
            model_name='invoicesleaddetail',
            name='header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.InvoicesLeadHeader'),
        ),
    ]
