# Generated by Django 2.2.4 on 2021-02-20 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_auto_20191219_1738'),
        ('sales', '0024_auto_20210216_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesleadheader',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Company'),
        ),
    ]
