# Generated by Django 4.0.3 on 2022-04-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_invoicesleadheader_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationsdetail',
            old_name='quotation',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='quotationsheader',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='quotationsheader',
            name='sequence',
        ),
    ]
