# Generated by Django 4.0.3 on 2022-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_rename_quotation_quotationsdetail_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesheader',
            name='invoiceStatus',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='invoicesheader',
            name='invoiceType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
