# Generated by Django 4.0.3 on 2022-05-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_invoicesheader_invoicestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesheader',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
