# Generated by Django 4.0.3 on 2022-06-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_invoicesheader_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesheader',
            name='sequence',
            field=models.IntegerField(unique=True),
        ),
    ]
