# Generated by Django 4.0.3 on 2022-06-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_alter_invoicesheader_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesheader',
            name='invoiceStatus',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
