# Generated by Django 4.0.3 on 2022-06-09 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_auto_20191219_1738'),
        ('sales', '0031_alter_invoicesheader_invoicestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_points', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('type', models.CharField(max_length=1)),
                ('reference', models.CharField(max_length=200)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdUser', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.invoicesheader')),
            ],
        ),
    ]
