# Generated by Django 4.0.3 on 2022-06-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesheader',
            name='amount_points',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
