# Generated by Django 4.0.3 on 2026-01-29 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_auto_20191219_1738'),
        ('sales', '0033_invoicesheader_amount_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesheader',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.user'),
        ),
    ]
