# Generated by Django 2.2.4 on 2019-08-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('descriptionLong', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('itbis', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('measure', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=50)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTracking', models.CharField(max_length=3)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company')),
                ('createdByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.User')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityAvailable', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantityHold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company')),
                ('modifiedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.User')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.User')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='companyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company'),
        ),
        migrations.AddField(
            model_name='product',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.User'),
        ),
    ]
