# Generated by Django 2.2.4 on 2019-08-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190830_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='companyId',
        ),
    ]
