# Generated by Django 2.2.4 on 2019-08-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_fiscalgov_current'),
        ('products', '0005_remove_productcategory_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='companyId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Company'),
        ),
    ]
