# Generated by Django 2.2.4 on 2019-08-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategory_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='companyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Company'),
        ),
    ]
