# Generated by Django 2.2.4 on 2019-08-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190830_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptionLong',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
