# Generated by Django 2.2.4 on 2019-09-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190831_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='companyId',
            new_name='company',
        ),
    ]
