# Generated by Django 2.2.4 on 2019-09-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190903_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='productsstock',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='productsstock',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productstracking',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='productstracking',
            old_name='productId',
            new_name='product',
        ),
    ]
