# Generated by Django 2.2.4 on 2019-09-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190903_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdByUser',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='createdByUser',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productsstock',
            name='modifiedByUser',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productstracking',
            name='createdByUser',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
