# Generated by Django 2.2.4 on 2019-09-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190930_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdByUser',
            new_name='createdUser',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='createdByUser',
            new_name='createdUser',
        ),
        migrations.RenameField(
            model_name='productsstock',
            old_name='modifiedByUser',
            new_name='modifiedUser',
        ),
        migrations.RenameField(
            model_name='productstracking',
            old_name='createdByUser',
            new_name='createdUser',
        ),
    ]
