# Generated by Django 2.2.4 on 2019-10-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190930_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstracking',
            name='concept',
            field=models.CharField(default='INVE', max_length=4),
        ),
    ]
