# Generated by Django 2.2.4 on 2019-11-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productstracking_headerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstracking',
            old_name='headerId',
            new_name='header',
        ),
    ]
