# Generated by Django 2.2.4 on 2019-11-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191121_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstrackingheader',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
