# Generated by Django 2.2.4 on 2019-11-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20191126_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstracking',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductsTrackingHeader'),
        ),
    ]
