# Generated by Django 2.2.4 on 2019-12-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20191219_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstrackingheader',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productstrackingheader',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
