# Generated by Django 2.2.4 on 2020-03-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20191230_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimumStock',
            field=models.IntegerField(default=0),
        ),
    ]
