# Generated by Django 2.2.4 on 2020-03-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_purchaseorder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
