# Generated by Django 2.2.4 on 2021-01-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200401_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsstock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
