# Generated by Django 2.2.4 on 2021-06-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210130_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
