# Generated by Django 4.0.3 on 2022-03-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsstock',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='ocurrences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsstock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stocks', serialize=False, to='products.product'),
        ),
        migrations.AlterField(
            model_name='productstracking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='products.product'),
        ),
    ]
