# Generated by Django 4.0.3 on 2022-06-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_productsstock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_max',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
